[package]
name = "ypsilot"
version = "0.1.0"
authors = ["ground-bound-sound <eofspe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.31.0", features = [ ] }
nalgebra = "0.18.0"
